# Generated by Django 2.1.5 on 2019-03-21 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='adiniz')),
                ('sname', models.CharField(max_length=120, verbose_name='soyadiniz')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('g', models.DateField(verbose_name='gorush')),
                ('s', models.TimeField(verbose_name='saat')),
                ('d', models.BooleanField(verbose_name='vur gtsn')),
                ('create_data', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_data', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitab', models.CharField(max_length=120)),
                ('yazar', models.CharField(max_length=120)),
                ('nov', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('shoes', 'shoes')], max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('qiymet', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('image', models.ImageField(upload_to='')),
                ('satis', models.CharField(choices=[('satilir', 'satilir'), ('kiraye', 'kiraye'), ('deyisdirilir', 'deyisdirilir')], max_length=120)),
                ('publish', models.DateTimeField(auto_now=True, verbose_name='Tarix')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish', 'id'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cart.Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
