# Generated by Django 2.1.5 on 2019-03-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='d',
            field=models.BooleanField(verbose_name='Sertleri qebul edirem'),
        ),
    ]
